// Auto-generated by scripts/split_dialogue.cjs
import berylData from './driftwatch/beryl.json';
import kaelenData from './driftwatch/kaelen.json';
import cyrusData from './driftwatch/cyrus.json';
import adaliaData from './driftwatch/adalia.json';
import matthiasData from './driftwatch/matthias.json';
import rodrickData from './driftwatch/rodrick.json';
import boricData from './driftwatch/boric.json';
import eliasData from './driftwatch/elias.json';
import robertaData from './driftwatch/roberta.json';
import marenClothierData from './driftwatch/maren_clothier.json';
import cassianJewelerData from './driftwatch/cassian_jeweler.json';
import finnData from './driftwatch/finn.json';
import oldCrankData from './driftwatch/old_crank.json';
import oldLeoData from './driftwatch/old_leo.json';
import crawlerData from './driftwatch/crawler.json';
import ronaldData from './driftwatch/ronald.json';
import benData from './driftwatch/ben.json';
import elisaData from './driftwatch/elisa.json';
import rowanData from './driftwatch/rowan.json';
import sarahData from './driftwatch/sarah.json';
import robertData from './driftwatch/robert.json';
import kyleData from './driftwatch/kyle.json';
import elaraData from './driftwatch/elara.json';
import barkipData from './driftwatch/barkip.json';
import stanData from './driftwatch/stan.json';
import shakyJaceData from './driftwatch/shaky_jace.json';
import shihanData from './driftwatch/shihan.json';
import linShaoData from './driftwatch/lin_shao.json';
import weiTarenData from './driftwatch/wei_taren.json';
import qiaoRenData from './driftwatch/qiao_ren.json';

const dialogueData = {
  ...berylData,
  ...kaelenData,
  ...cyrusData,
  ...adaliaData,
  ...matthiasData,
  ...rodrickData,
  ...boricData,
  ...eliasData,
  ...robertaData,
  ...marenClothierData,
  ...cassianJewelerData,
  ...finnData,
  ...oldCrankData,
  ...oldLeoData,
  ...crawlerData,
  ...ronaldData,
  ...benData,
  ...elisaData,
  ...rowanData,
  ...sarahData,
  ...robertData,
  ...kyleData,
  ...elaraData,
  ...barkipData,
  ...stanData,
  ...shakyJaceData,
  ...shihanData,
  ...linShaoData,
  ...weiTarenData,
  ...qiaoRenData
};

export default dialogueData;
