const fs = require('fs');
const path = require('path');

const dialoguePath = path.join(__dirname, '../src/data/dialogue.json');
const outputDir = path.join(__dirname, '../src/data/dialogues');
const driftwatchDir = path.join(outputDir, 'driftwatch');
const data = JSON.parse(fs.readFileSync(dialoguePath, 'utf8'));

if (!fs.existsSync(driftwatchDir)) {
  fs.mkdirSync(driftwatchDir, { recursive: true });
}

const fileMap = {};
const keyMap = {
  'old': 'old_crank',
  'shaky': 'shaky_jace'
};

Object.keys(data).forEach(key => {
  const prefix = key.split('_')[0];
  const filename = keyMap[prefix] || prefix;
  
  if (!fileMap[filename]) {
    fileMap[filename] = {};
  }
  
  fileMap[filename][key] = data[key];
});

const imports = [];
const exportedData = [];

Object.keys(fileMap).forEach(filename => {
  const filePath = path.join(driftwatchDir, `${filename}.json`);
  fs.writeFileSync(filePath, JSON.stringify(fileMap[filename], null, 2));
  console.log(`Created driftwatch/${filename}.json`);
  
  const varName = filename.replace(/_([a-z])/g, (g) => g[1].toUpperCase()) + 'Data'; // camelCaseData
  imports.push(`import ${varName} from './driftwatch/${filename}.json';`);
  exportedData.push(`...${varName}`);
});

const indexContent = `// Auto-generated by scripts/split_dialogue.cjs
${imports.join('\n')}

const dialogueData = {
  ${exportedData.join(',\n  ')}
};

export default dialogueData;
`;

fs.writeFileSync(path.join(outputDir, 'index.ts'), indexContent);
console.log('Created index.ts');
